### ISSUE TITLE
`yubikey` module: tracking issue for core functionality (auth, encrypt, sign)

### ISSUE THREAD

**Issue by tarcieri** [iqlusioninc/yubikey.rs#20]
This issue is for tracking work on the `yubikey` module, whose primary API is the `YubiKey` type which provides the main entrypoint for using the library.

If you are interested in testing or working on any of the functions below, please leave a comment in this issue.

Below are the functions in this module and their current status:

|       | Name                    | Testing                 | Description                               | Notes |
|----| -----------------| -----------------|------------------------------|-------|
| ✅| `open`                  | `integration.rs`   |  open connection to YubiKey | rename to `connect` ? |
| ⚠️ | `reconnect`          | *none*                  | reconnect old session            | make private/automatic? |
| ✅ | `version`              | manual                  | get device version                   | fetched at `open` |
| ✅ | `serial`                 | manual                  | get device serial                       | fetched at `open` |
| ⚠️ | `device_model`    | *none*                  | get device model (NEOr3/YK4+) | can't distinguish YK5? |
| ⚠️ | `authenticate`      | *none*                  | auth with MGM key                 | move to `mgm` module? |
| ⚠️ | `deauthenticate`  | *none*                  | close auth'd card session      | |
| ✅| `verify_pin`           | *none*                  | check if entered PIN is correct |
| ⚠️ | `get_pin_retries`  | *none*                  | get number of remaining tries |
| ⚠️ | `set_pin_retries`  | *none*                  | set number of remaining tries |
| ⚠️ | `change_pin`       | *none*                  | change device PIN |
| ⚠️ | `set_pin_last_changed`  | *none*      | set time of last PIN change | make this automatic? |
| ⚠️ | `chain_puk`           | *none*                  | change PIN Unblocking Key (PUK) | 
| ⚠️ | `block_puk`           | *none*                  | block PUK from being usable | can only be cleared with device reset! |
| ⚠️ | `unblock_pin`        | *none*                  | reset (blocked) PIN using PUK |
| ⚠️ | `get_auth_challenge`  | *none*              | get MGM challenge message | move to `mgm` module? |
| ⚠️ | `verify_auth_response`  | *none*           | verify MGM auth response      | move to `mgm` module? |
| ⚠️ | `reset_device`                | *none*           | clear device; reset to default state | only works if PIN/PUK are blocked?|

Legend:

|       | Description                |
|----|---------------------|
| ✅ | Tested and working |
| ⚠️  | Untested                    |

**Comment by tony-iqlusion** [comment]
Closing these issues as the API has been flattened in #274.
