### ISSUE TITLE
`mgm` module: tracking issue for Management Key (MGM) support (e.g. get, set, derive)

### ISSUE THREAD

**Issue by tarcieri** [iqlusioninc/yubikey.rs#27]
This issue is for tracking work on the `mgm` module.

**Comment by str4d** [comment]
I think it makes sense for the management key and its metadata to be in one of four states:

- The default key.
- A user-supplied custom key.
- A derived key.
- A PIN-protected key (optionally custom, but defaulting to a new random key).

All of these could have optional touch requirements.

The current APIs are:
- `MgmKey::set(yubikey, touch: Option<u8>)`
  - Replaces the existing management key (using the given touch requirement).
- `MgmKey::set_protected(yubikey)`
  - Replaces the existing management key (using no touch requirement).
  - Saves the new key in the PIN-protected metadata.
  - Sets the corresponding admin metadata flag bit.
  - Removes any existing derived mgm salt.

`MgmKey::set_protected(yubikey)` provides an effective transtion from any existing state to "PIN-protected", but `MgmKey::set(yubikey, touch: Option<u8>)` leaves the YubiKey in an indeterminate metadata state (the newly-set `MgmKey` will work regardless).

We should either have `MgmKey::set` take a `MgmType` parameter, or (my preference) have separate APIs for setting each of the four states.

**Comment by tony-iqlusion** [comment]
Sounds good to me

**Comment by tony-iqlusion** [comment]
Closing these issues as the API has been flattened in #274.
