### ISSUE TITLE
`write_certificate` is not exposed

### ISSUE THREAD

**Issue by obelisk** [iqlusioninc/yubikey.rs#321]
I'd like to use this function to load in a certificate generated by an external authority but the only way I see to write a certificate is to generate a self signed one.

Is there any harm is building a `pub` wrapper around the `pub(crate) write_certificate` function to allow this?

**Comment by tony-iqlusion** [comment]
I think it would be fine to change `write_certificate` to be `pub`.

Curious what @str4d thinks.
