### ISSUE TITLE
Support for ECDH?

### ISSUE THREAD

**Issue by vdods** [iqlusioninc/yubikey.rs#366]
As per the readme, this is indeed the crate I have been looking for!

I'm wondering if implementing ECDH key agreement is on the roadmap.  It's described [here](https://docs.yubico.com/yesdk/users-manual/application-piv/apdu/auth-key-agree.html).  It doesn't look terribly difficult to hook up.  I'd like to know if anyone has taken a start at implementing this before I give it a crack.  If I can get it working, would a PR be welcome?

**Comment by vdods** [comment]
Hmm.. upon a closer look, it looks like piv::decrypt_data might actually achieve this if you plug in the other party's public key in the expected format (as described in the linked doc).  Is this right?

**Comment by str4d** [comment]
Indeed this is the case. My primary motivation for working on this crate was to enable using P-256 keys on YubiKeys for `age` decryption. See [my `age-plugin-yubikey` crate](https://github.com/str4d/age-plugin-yubikey/blob/b3590f4ce1f570be34aa5d132840d4a7122c67b2/src/key.rs#L422-L432) for how it is used.

**Comment by vdods** [comment]
Awesome, thanks for the heads up, I was able to get it working :-)
