### ISSUE TITLE
Requesting release for RustCrypto crate updates

### ISSUE THREAD

**Issue by indygreg** [iqlusioninc/yubikey.rs#393]
Thanks for this terrific crate! (I'm unsure if you are aware but I'm leveraging this crate in my pure Rust implementation of Apple code signing and it has been mostly a breeze to work with: https://gregoryszorc.com/docs/apple-codesign/main/)

I'm currently stuck in dependency hell trying to upgrade RustCrypto crates. Would it be possible to get a new release of this crate with upgraded dependencies? The latest `main` commit with rsa 0.6 should be sufficient. I could cobble together some PRs to upgrade `der-parser`, `p384`, `sha2`, and/or `x509-parser` if that would help. (But it looks like dependabot may have beat me to some of it.)

**Comment by tony-iqlusion** [comment]
I'll take a look at this soon

**Comment by indygreg** [comment]
Is there anything I can do to help this along?

**Comment by tony-iqlusion** [comment]
I'll get to it soon, just getting through a few dozen other RustCrypto crate releases

**Comment by tony-iqlusion** [comment]
Released in #403

**Comment by indygreg** [comment]
Thank you so much! I'm still working through the API changes to all the RustCrypto crates. But the dependency resolver is able to work with the newest versions of all the crates and that's the important part.
