### ISSUE TITLE
Enable library users to detect if a smart card doesn't support PIV

### ISSUE THREAD

**Issue by str4d** [iqlusioninc/yubikey.rs#456]
In https://github.com/str4d/age-plugin-yubikey/issues/78 a user has run into an issue where their Windows installation has an OS-provided virtual smart card which is always connected and doesn't support PIV. Currently, this causes a generic error to be returned by `yubikey`:

https://github.com/iqlusioninc/yubikey.rs/blob/002491193eb49274ec20e2ac4c4305fec4364ee1/src/transaction.rs#L68-L88

We should instead detect the case where we fail to select the PIV application (ideally specifically detecting the status code for "does not exist") and expose this to the caller, so they can match on it in some way to ignore unusable smart cards.

**Comment by str4d** [comment]
I can't find a reference for this, but from some Googling it looks like `response.status_words().code() == 0x6a82` should be interpreted as "application not found".

**Comment by tony-iqlusion** [comment]
I believe it's defined in [ISO/IEC 7816-4](https://www.iso.org/standard/77180.html) however confirming that would unfortunately cost CHF 198, unless we know anyone who already has access (I might)

**Comment by str4d** [comment]
Yeah, "file not found" is what I also see elsewhere documented for that status code, but it is also the status code that (at least in the cases I've seen) is returned when `Ins::SelectApplication` can't find the specified applet. I'm guessing it was reused for convenience (or maybe because the smart cards are literally failing to find the file that the applet is stored in, that they want to run).

**Comment by tony-iqlusion** [comment]
Oh yeah, I agree, in that context "file not found" actually means "applet not found"

**Comment by str4d** [comment]
https://github.com/str4d/age-plugin-yubikey/pull/110 has another example of this occurring: an Alcor Micro AU9540 Smartcard reader that (when no smartcard is inserted) is sufficiently responsive to give some details, but returns this same error when trying to select the PIV applet (instead of returning `pcsc::Error::NoSmartcard` or `pcsc::Error::RemovedCard`.
